### ISSUE TITLE
Add a survey paper

### ISSUE THREAD

**Issue by tfzhou** [uncbiag/Awesome-Foundation-Models#3]
Thanks for your efforts in maintaining the great repo. 

I'd like to introduce our recent survey paper "Image Segmentation in Foundation Model Era: A Survey", which is closely related to the topic of the repo. arXiv: [https://arxiv.org/pdf/2408.12957](https://arxiv.org/pdf/2408.12957)

Could you please add the article in your repo? Thanks in advance

**Comment by qinliuliuqin** [comment]
Thank you, Tianfei. Just added your wonderful survey. 

Sec. 5.1.1 seems to have a typo. "Most existing interactive segmentation methods determines [-> determine] ... " 

Besides, you mentioned existing interactive segmentation methods, but no citations provided. It would be great if you consider providing a little bit more context here for general readers. For example, mentioning the differences/contributions of SAM over traditional interactive segmentation methods (e.g., SimpleClick ICCV'23 and FocalClick CVPR'22, both were compared as baselines in SAM). 

Additional thoughts. From my point of view, SAM made the following major contributions over traditional interactive segmentation methods.
- Ambiguity-aware segmentation, and thus better performance on the Segment Anything task, which is also first introduced in SAM.
- Leveraging a large-scale training dataset (SAM-1B) and large MAE pretrained ViT backbones. SimpleClick also adopted MAE pretrained ViT backbones, but no web-scale training data.
- Late fusion design for efficient prompting. This design, however, was first proposed in InterFormer (ICCV'23).

**Comment by tfzhou** [comment]
@qinliuliuqin Thanks for the insightful comments and I agree most of them. We will improve relevant parts in the next version. We are also happy to include the papers you mentioned. Thanks.
