### ISSUE TITLE
Add a CVPR 2024 paper

### ISSUE THREAD

**Issue by hellomuffin** [uncbiag/Awesome-Foundation-Models#4]
Could you add our CVPR 2024 paper about vision-language pertaining, "Iterated Learning Improves Compositionality in Large Vision-Language Models", into this repo?

Paper link: https://arxiv.org/abs/2404.02145
github: https://github.com/hellomuffin/iterated-learning-for-vlm

**Comment by qinliuliuqin** [comment]
Added.
